### ISSUE TITLE
KeyError in btreesupport

### ISSUE THREAD

**Issue by mgedmin** [mgedmin/zodbbrowser#15]
Saw this at http://localhost:8070/@@zodbbrowser?oid=0x3da6f&tid=0x35ff6a3c086a288:

```
Traceback (most recent call last):
  File "/srv/zopes/akl-2.13/eggs/zodbbrowser-0.12.0-py2.6.egg/zodbbrowser/browser.py", line 94, in __call__
    return self.render()
  File "/srv/zopes/akl-2.13/eggs/zodbbrowser-0.12.0-py2.6.egg/zodbbrowser/browser.py", line 134, in render
    _history=self.history)
  File "/srv/zopes/akl-2.13/eggs/zodbbrowser-0.12.0-py2.6.egg/zodbbrowser/state.py", line 88, in __init__
    self._load()
  File "/srv/zopes/akl-2.13/eggs/zodbbrowser-0.12.0-py2.6.egg/zodbbrowser/state.py", line 101, in _load
    IStateInterpreter)
  File "/srv/zopes/akl-2.13/eggs/zope.component-3.9.5-py2.6.egg/zope/component/_api.py", line 107, in getMultiAdapter
    adapter = queryMultiAdapter(objects, interface, name, context=context)
  File "/srv/zopes/akl-2.13/eggs/zope.component-3.9.5-py2.6.egg/zope/component/_api.py", line 120, in queryMultiAdapter
    return sitemanager.queryMultiAdapter(objects, interface, name, default)
  File "/srv/zopes/akl-2.13/eggs/zope.component-3.9.5-py2.6.egg/zope/component/registry.py", line 238, in queryMultiAdapter
    objects, interface, name, default)
  File "/srv/zopes/akl-2.13/eggs/zope.interface-3.6.7-py2.6-linux-i686.egg/zope/interface/adapter.py", line 532, in queryMultiAdapter
    result = factory(*objects)
  File "/srv/zopes/akl-2.13/eggs/zodbbrowser-0.12.0-py2.6.egg/zodbbrowser/btreesupport.py", line 109, in __init__
    state = IObjectHistory(bucket).loadState(tid)
  File "/srv/zopes/akl-2.13/eggs/zodbbrowser-0.12.0-py2.6.egg/zodbbrowser/history.py", line 89, in loadState
    return self._connection.oldstate(self._obj, self.lastChange(tid))
  File "/srv/zopes/akl-2.13/eggs/zodbbrowser-0.12.0-py2.6.egg/zodbbrowser/history.py", line 82, in lastChange
    (self._obj, tid_repr(tid)))
KeyError: "BTrees.OOBTree.OOBucket([('AKL', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x07\\xd4K'>), ('AKL2004', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x07\\xd4\\x98'>), ('AKL2006Planai', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x08\\x02\\xcb'>), ('AKLActivities', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x07\\xd43'>), ('AKLDomenai', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x07\\xd4\\x0f'>), ('AKLEnglish', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x07\\xd4\\\\'>), ('AKLMainPuslapio', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x07\\xd4\\x0c'>), ('AKLMetrastis', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x07\\xf2\\x84'>), ('AKLVeiklos', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x07\\xd4v'>), ('AKLVisuotinis2009', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\t\\xc0\\xcb'>), ('AKLVisuotinis2012', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\t\\xdc\\xe7'>), ('AKMoksliniaiDarbai', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x08\\x93\\x0b'>), ('AKMoksliniaiDarbai.old', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x08\\x93\\x04'>), ('AKMokykla', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\t\\x84/'>), ('AKSekmesIstorijos', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x07\\xd4b'>), ('ALFProjektai', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x07\\xd4\\x91'>), ('AnnoyingQuote', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x07\\xd4\\xa7'>), ('Apdovanojimai', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x07\\xd4\\x86'>), ('ApklausosAnketaRenginiams', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x08\\xcc\\xa4'>), ('ArtimiausiasMytas', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x07\\xd4|'>), ('AtliktuDarbu', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x07\\xd4>'>), ('Atributika', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x07\\xd4<'>), ('AtvirasKodasSvietimui', <persistent broken Products.ZWiki.ZWikiPage.ZWikiPage instance '\\x00\\x00\\x00\\x00\\x00\\x07\\xd3\\xe8'>)]) did not exist in or before transaction '0x035ff6a3c086a288'"
```

pdb gives me this, in OOBTreeState.\_\_init\_\_:

```
(Pdb) p u64(tid)
243184088071447176L
(Pdb) p hex(u64(tid))
'0x35ff6a3c086a288L'
(Pdb) p hex(u64(self.state[1]._p_oid))
'0x7d4bc'
```

pdb gives me this, in lastChange():

```
(Pdb) p hex(u64(self._obj._p_oid))
'0x7d4bc'
(Pdb) pp u64(tid)
243184088071447176L
(Pdb) pp [u64(r['tid']) for r in self._history]
[258983429170728686L, 251710657918737868L]
```

pdb gives me this, in ZodbObjectState._load():

```
(Pdb) p hex(u64(self.obj._p_oid))
'0x3da6f'
(Pdb) p [u64(r['tid']) for r in self.history._history]
[253388639622379434L, 243184088071447176L]
```

Very mysterious.  Two problems here:
- somehow the historical btree state cannot be resolved
- the error is not captured and contained ([because it happens after the try/except that contains load errors](https://github.com/mgedmin/zodbbrowser/blob/66ae3527d2287a35845745f8779d06037d08bdfa/src/zodbbrowser/state.py#L99-L101))

**Comment by mgedmin** [comment]
I'm wishing ZODBBrowser had a simple API to get the state pickle from (oid, tid) pair, without having to have the object itself.

I think I'll need the BTree storage format docs for the description of [BTree.\__getstate__()](https://github.com/zopefoundation/BTrees/blob/b49be3c9599fb0a11a3a71858727c11e2f962f68/BTrees/BTreeTemplate.c#L1065-L1087) and [Bucket.\__getstate__()](https://github.com/zopefoundation/BTrees/blob/b49be3c9599fb0a11a3a71858727c11e2f962f68/BTrees/BucketTemplate.c#L1182-L1200).

**Comment by mgedmin** [comment]
Ok, we have a BTrees.OOBTree.OOBTree with oid 0x3da6f and two state pickles:

- t=253388639622379434 links to bucket 0x7d4bc
- t=243184088071447176 links to bucket ???

Bucket 0x7d4bc has two state pickles:

- t=258983429170728686 links to bucket ???
- t=251710657918737868 links to bucket ???

This is tedious to debug with pdb.  Perhaps @@zodbbrowser ought to get a raw mode where it would show me a disassembly of the pickles themselves?

**Comment by mgedmin** [comment]
> the error is not captured and contained (because it happens after the try/except that contains load errors)

This part was fixed in 0e85bafbc7f9a3dcc237f66c24382efa4ab0b107.

**Comment by mgedmin** [comment]
> Perhaps @@zodbbrowser ought to get a raw mode where it would show me a disassembly of the pickles themselves?

This happened in 54ee63d8f8560c4e7f0e52e35dbd9c3fdc808778.

**Comment by mgedmin** [comment]
This bug is similar to #29 

I don't have the Data.fs that caused this handy, so I'm not sure I'll be able to fix it.  Perhaps containment will be enough.
