### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by mgedmin** [mgedmin/zodbbrowser#27]
Something changed yesterday and all builds fail now.

Compare:

- https://travis-ci.org/mgedmin/zodbbrowser/jobs/318527624 (last build - bad)
- https://travis-ci.org/mgedmin/zodbbrowser/jobs/317625343 (previous build - good)

The error itself is in zope.app.testing
```
Traceback (most recent call last):
  File "/home/travis/build/mgedmin/zodbbrowser/src/zodbbrowser/ftests/test_standalone.py", line 23, in <module>
    from zope.app.testing import setup
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/zope/app/testing/setup.py", line 59, in <module>
    from zope.app.testing.placelesssetup import setUp as placelessSetUp
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/zope/app/testing/placelesssetup.py", line 32, in <module>
    ContainerPlacelessSetup):
TypeError: Error when calling the metaclass bases
    Cannot create a consistent method resolution
order (MRO) for bases PlacelessSetup, PlacelessSetup, PlacelessSetup, CleanUp
```

**Comment by mgedmin** [comment]
It's somehow caused by zope.i18n 4.3.0.  Downgrading to 4.2.0 makes the error go away.

**Comment by mgedmin** [comment]
Filed https://github.com/zopefoundation/zope.i18n/issues/30
