### ISSUE TITLE
Exception: Failed to execute command: '/usr/bin/python3', '-c', "import sys; sys.path[0:0] = ['/home/walter/.local/lib/python3.8/site-packages']; from setuptools.command.easy_install import main; main()", '-mZqNxd', '/tmp/bootstrap-lhakrly7', 'zc.buildout==2.13.6'

### ISSUE THREAD

**Issue by walter-weinmann** [mgedmin/zodbbrowser#35]
## Environment:

- Ubuntu 20.04 LTS incl. build-essentials, python3-dev, python3-pip, python3-zc.buildout, zlibg1
- Python 3.8 

```
walter@ubuntu:~/zodbbrowser$ python3 --version
Python 3.8.10
```

## Issue:

```
walter@ubuntu:~/zodbbrowser$ python3 bootstrap.py
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
/home/walter/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'main' from 'setuptools.command.easy_install' (/home/walter/.local/lib/python3.8/site-packages/setuptools/command/easy_install.py)
Traceback (most recent call last):
  File "bootstrap.py", line 192, in <module>
    raise Exception(
Exception: Failed to execute command:
'/usr/bin/python3', '-c', "import sys; sys.path[0:0] = ['/home/walter/.local/lib/python3.8/site-packages']; from setuptools.command.easy_install import main; main()", '-mZqNxd', '/tmp/bootstrap-lhakrly7', 'zc.buildout==2.13.6'
```

## pip freeze

```
/home/walter/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/walter/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
apturl==0.5.2
bcrypt==3.1.7
blinker==1.4
Brlapi==0.7.0
certifi==2019.11.28
chardet==3.0.4
Click==7.0
colorama==0.4.3
command-not-found==0.3
cryptography==2.8
cupshelpers==1.0
dbus-python==1.2.16
defer==1.0.6
distro==1.4.0
distro-info===0.23ubuntu1
duplicity==0.8.12.0
entrypoints==0.3
fasteners==0.14.1
future==0.18.2
httplib2==0.14.0
idna==2.8
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lockfile==0.12.2
louis==3.12.0
macaroonbakery==1.3.1
Mako==1.1.0
MarkupSafe==1.1.0
monotonic==1.5
netifaces==0.10.4
oauthlib==3.1.0
olefile==0.46
paramiko==2.6.0
pbr==5.8.0
pexpect==4.6.0
Pillow==7.0.0
protobuf==3.6.1
pycairo==1.16.2
pycups==1.9.73
PyGObject==3.36.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyRFC3339==1.1
python-apt==2.0.0+ubuntu0.20.4.6
python-dateutil==2.7.3
python-debian===0.1.36ubuntu1
pytz==2019.3
pyxdg==0.26
PyYAML==5.3.1
reportlab==3.5.34
requests==2.22.0
requests-unixsocket==0.2.0
SecretStorage==2.3.1
simplejson==3.16.0
six==1.14.0
systemd-python==234
testresources==2.0.1
ubuntu-advantage-tools==27.4
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
usb-creator==0.3.7
wadllib==1.3.3
xkit==0.0.0
zc.buildout==2.13.2

```

**Comment by mgedmin** [comment]
IIRC buildout's bootstrap.py is incompatible with modern setuptools version, and buildout's upstream recommends using `pip install zc.buildout; buildout bootstrap` instead.

I'll update the Makefile and the README.

Note that buildout is only used for developing zodbbrowser itself; it's enough to `pip install it` if all you want to use it.  And even for development I no longer think buildout is worth the headaches and I'm considering getting rid of it.  tox + a simple Makefile for setting up a local virtualenv ought to be enough.

**Comment by mgedmin** [comment]
Oh wow the README was outdated way more than I remembered!  easy_install, good heavens.  Usage with pip is definitely no longer experimental, and the bit about hardcoded known-working versions in buildout.cfg is no longer true.

**Comment by walter-weinmann** [comment]
@mgedmin  Hi Marius - thank you very much for the quick response - it is working now for me.
